% Odometry model used in Eric Perko's thesis.
odom1 = @(x,y,theta,v,omega,dt) ...
        [x + v*dt*cos(theta); ...
         y + v*dt*sin(theta); ...
         theta + omega*dt; ...
         v + 0*dt; ... 0*dt used for dt of variable length
         omega + 0*dt];
% Odometry model used in EJ Kreiner's thesis.
odom2 = @(x,y,theta,v,omega,dt) ...
        [x + v*dt.*cos(theta+omega*dt/2); ...
         y + v*dt.*sin(theta+omega*dt/2); ...
         theta + omega*dt; ...
         v + 0*dt; ...
         omega + 0*dt];
% Odometry model described in Wang 1988.
odom3 = @(x,y,theta,v,omega,dt) ...
        [x + (sin(omega*dt/2)./(omega*dt/2))*v.*dt.*cos(theta+omega*dt/2); ...
         y + (sin(omega*dt/2)./(omega*dt/2))*v.*dt.*sin(theta+omega*dt/2); ...
         theta + omega*dt; ...
         v + 0*dt; ...
         omega + 0*dt];