% x (a vector) is the state of the robot. The elements of the vector, in
% order are x position (x), y position (y), heading (theta), linear
% velocity (v), angular velocity (omega)

% Odometry model used in Eric Perko's thesis.
odom1 = @(x,dt) ...
        [x(1) + x(4)*dt*cos(x(3)); ...
         x(2) + x(4)*dt*sin(x(3)); ...
         x(3) + x(5)*dt; ...
         x(4) + 0*dt; ... 0*dt used for dt of variable length
         x(5) + 0*dt];
% Odometry model used in EJ Kreiner's thesis.
odom2 = @(x,dt) ...
        [x(1) + x(4)*dt.*cos(x(3)+x(5)*dt/2); ...
         x(2) + x(4)*dt.*sin(x(3)+x(5)*dt/2); ...
         x(3) + x(5)*dt; ...
         x(4) + 0*dt; ...
         x(5) + 0*dt];
% Odometry model described in Wang 1988.
odom3 = @(x,dt) ...
        [x(1) + (sin(x(5)*dt/2)./(x(5)*dt/2))*x(4).*dt.*cos(x(3)+x(5)*dt/2); ...
         x(2) + (sin(x(5)*dt/2)./(x(5)*dt/2))*x(4).*dt.*sin(x(3)+x(5)*dt/2); ...
         x(3) + x(5)*dt; ...
         x(4) + 0*dt; ...
         x(5) + 0*dt];
