% Odometry model used in Eric Perko's thesis.
odom1 = @(x,y,theta,v,omega,dt) ...
        [x + v*dt*cos(theta); ...
         y + v*dt*sin(theta); ...
         theta + omega*dt; ...
         v; ...
         omega];
% Odometry model used in EJ Kreiner's thesis.
odom2 = @(x,y,theta,v,omega,dt) ...
        [x + v*dt.*cos(theta+omega*dt/2); ...
         y + v*dt.*sin(theta+omega*dt/2); ...
         theta + omega*dt; ...
         v; ...
         omega];
% Odometry model described in Wang 1988.
odom3 = @(x,y,theta,v,omega,dt) ...
        [x + (sin(omega*dt/2)./(omega*dt/2))*v.*dt.*cos(theta+omega*dt/2); ...
         y + (sin(omega*dt/2)./(omega*dt/2))*v.*dt.*sin(theta+omega*dt/2); ...
         theta + omega*dt; ...
         v; ...
         omega];